services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_USERNAME=devantler
      - MONGO_PASSWORD=password
      - MONGO_DB_NAME=admin
      - REDIS_URI=redis://redis:6379
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devantler
      - MONGO_INITDB_ROOT_PASSWORD=password