name: Build and test
on:
  pull_request:
  push: 
    branches: 
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Frontend
        run: cd Frontend; npm install; CI=false && npm run build;

  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Backend
        run: cd Backend; npm install; npm run build;
  
  auto-merge:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-22.04
    steps:
      - uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: "SQUASH"
