name: Publish Images and Terraform CI
on:
    workflow_dispatch:
    push:
        branches: [master]

env:
    GC_PROJECT_ID: formal-vertex-364508

jobs:
  build-and-publish-ccecaa-frontend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add metadata to image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository_owner }}/ccecaa-frontend

      - name: Build and load image with caching
        uses: docker/build-push-action@v3
        with:
          context: Frontend/
          file: Frontend/Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push image to Google Container Registry
        uses: mattes/gce-docker-push-action@v1
        with:
            creds: ${{ secrets.GOOGLE_CREDENTIALS }}
            src: ${{ github.repository_owner }}/ccecaa-frontend:master
            dst: gcr.io/${{ env.GC_PROJECT_ID }}/ccecaa-frontend:latest

  build-and-publish-ccecaa-backend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add metadata to image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository_owner }}/ccecaa-backend

      - name: Build and load image with caching
        uses: docker/build-push-action@v3
        with:
          context: Backend/
          file: Backend/Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push image to Google Container Registry
        uses: mattes/gce-docker-push-action@v1
        with:
            creds: ${{ secrets.GOOGLE_CREDENTIALS }}
            src: ${{ github.repository_owner }}/ccecaa-backend:master
            dst: gcr.io/${{ env.GC_PROJECT_ID }}/ccecaa-backend:latest

  terraform:
    needs: [build-and-publish-ccecaa-frontend, build-and-publish-ccecaa-backend]
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: terraform
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Terraform to be used in the GitHub Action
        uses: hashicorp/setup-terraform@v2
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN}}

      - run: terraform init

      - run: terraform plan -replace
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - run: terraform apply -auto-approve -replace
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
