name: Industrial Report 2 Document Conversion

on: 
  pull_request: 
    branches: ["master"]

env:
  FILE_NAME: industrial-report2
  PROJECT_PATH: reports/industrial-report2/
  PANDOC_VERSION: 2.18
  PLANTUML_VERSION: 1.2022.6
  PANDOC_CROSSREF_VERSION: 0.3.13.0

jobs:
  convert_via_pandoc:
    name: Generate Industrial Report 2 with Pandoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update apt package registry
        run: sudo apt-get update -y
      - name: Install LaTeX packages
        run: sudo apt install -y texlive texlive-latex-extra
      - name: Install libsvg2-bin
        run: sudo apt install -y librsvg2-bin
      - name: Download plantuml.jar
        run: wget https://github.com/plantuml/plantuml/releases/download/v${{ env.PLANTUML_VERSION }}/plantuml-${{ env.PLANTUML_VERSION }}.jar -O plantuml.jar
        working-directory: ${{ env.PROJECT_PATH }}
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/${{ env.PANDOC_VERSION }}/pandoc-${{ env.PANDOC_VERSION }}-1-amd64.deb
          sudo dpkg -i pandoc-${{ env.PANDOC_VERSION }}-1-amd64.deb
      - name: Install pandoc-crossref
        run: |
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v${{ env.PANDOC_CROSSREF_VERSION }}/pandoc-crossref-Linux.tar.xz -O pandoc-crossref.tar.xz
          sudo tar -xvf pandoc-crossref.tar.xz -C /usr/bin/
          sudo chmod +x /usr/bin/pandoc-crossref
      - name: Convert *.md to pdf with pandoc
        run: pandoc -d main.yaml -o ${{ env.FILE_NAME }}.pdf content/*.md
        working-directory: ${{ env.PROJECT_PATH }}
      - name: Upload generated ${{ env.FILE_NAME }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.PROJECT_PATH }}${{ env.FILE_NAME }}.pdf
