name: Publish Images
on:
  workflow_dispatch:
  push:
    paths:
      - "Backend/**"
      - "Frontend/**"
      - ".github/workflows/publish-images.yaml"
    branches:
      - master

env:
    GC_PROJECT_ID: formal-vertex-364508

jobs:
  build-and-publish-ccecaa-frontend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: Frontend/
          file: Frontend/Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ github.repository_owner }}/ccecaa-frontend
      - name: list docker images
        run: docker image list
      - name: Push image to Google Container registry
        uses: mattes/gce-docker-push-action@v1
        with:
            creds: ${{ secrets.GOOGLE_CREDENTIALS }}
            src: ghcr.io/${{ github.repository_owner }}/ccecaa-frontend
            dst: gcr.io/${{ env.GC_PROJECT_ID }}/ccecaa-frontend:${{github.run_number}}-${{github.sha}}
  build-and-publish-ccecaa-backend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: Backend/
          file: Backend/Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ github.repository_owner }}/ccecaa-backend
      - name: list docker images
        run: docker image list
      - name: Push image to Google Container registry
        uses: mattes/gce-docker-push-action@v1
        with:
            creds: ${{ secrets.GOOGLE_CREDENTIALS }}
            src: ghcr.io/${{ github.repository_owner }}/ccecaa-backend
            dst: gcr.io/${{ env.GC_PROJECT_ID }}/ccecaa-backend:${{github.run_number}}-${{github.sha}}
