name: Terraform CI

on:
    push:
        branches: [master]

env:
    GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            - name: Setup Terraform to be used in the GitHub Action
              uses: hashicorp/setup-terraform@v2
            - name: Terraform Init
              run: terraform -chdir=terraform init
            - name: Terraform Format
              run: terraform -chdir=terraform fmt -check
            - name: Terraform Plan
              run: terraform -chdir=terraform plan
            - name: Terraform Apply
              run: terraform -chdir=terraform apply -auto-approve
