name: Terraform CI

on:
    push:
        branches: [master]

defaults:
  run:
    working-directory: terraform

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            - name: Setup Terraform to be used in the GitHub Action
              uses: hashicorp/setup-terraform@v2
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN}}
            - run: terraform init
            - run: terraform plan
            - run: terraform apply -auto-approve
            - name: TROELS IS A CUNT
              run: echo "Hey my name is troels and i am a cunt!"
