name: Terraform CI

on:
    push:
        branches: [master]

defaults:
  run:
    working-directory: terraform

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            - name: Setup Terraform to be used in the GitHub Action
              uses: hashicorp/setup-terraform@v2
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN}}
            - name: Terraform Init
              run: terraform init
              env:
                  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
            - name: Terraform Format
              run: terraform fmt -check
              continue-on-error: true
            - name: Terraform Plan
              run: terraform plan
            - name: Terraform Apply
              run: terraform apply -auto-approve
